#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('people.views', 
	url(r'^home/$', 'home', name='home'),
	url(r'^logout/$', 'people_logout', name='people_logout'),
	url(r'^(?P<pid>(\d+))/profile$', 'profile', name='profile'), 
	url(r'^fillinfo/$', 'fillinfo', name='fillinfo'),
	url(r'^newrecommend/$', 'newuser_recommend_follow', name='newuser_recommend'),
	url(r'^peopleinfo/(?P<pid>(\d+))/$', 'people_info', name='people_info'),
	url(r'^info/$', 'set_info', name='set_info'),
	url(r'settings/$', 'settings', name='settings'),
	url(r'^follow/(?P<pid>(\d+))/$', 'follow_page', name='follow_page'),
	url(r'^fan/(?P<pid>(\d+))/$', 'fan_page', name='fan_page'),
	url(r'^blacklist_page/$', 'blacklist_page', name='blacklist_page'),
	url(r'^follow_action', 'follow_action', name='follow_action'),
	url(r'^remove_fan', 'remove_fan', name='remove_fan'),
	url(r'^add_blacklist', 'add_blacklist', name='add_blacklist'),
	url(r'^remove_blacklist', 'remove_blacklist', name='remove_blacklist'),
	url(r'^get_relation_info', 'get_relation_info', name='get_relation_info'),
	url(r'^get_follow/$', 'get_follow', name='get_follow'),
	url(r'^match_nickname/$', 'match_nickname', name='match_nickname'),
	url(r'^match_domainurl', 'match_domainurl', name='match_domainurl'),
	url(r'^match_password', 'match_password', name='match_password'),
	url(r'^update_password', 'update_password', name='update_password'),
	url(r'^update_background', 'update_background', name='update_background'),
	url(r'^update_mode', 'update_mode', name='update_mode'),
	url(r'^private_shema', 'private_schema', name='private_schema'),
	url(r'^remind_schema', 'remind_schema', name='remind_schema'),
	url(r'^get_background/(?P<pid>(\d+))/$', 'get_background', name='get_background'),
)

